### ISSUE TITLE
addauthorization creates the ExpressRoute auth key but responds with BadRequest

### ISSUE THREAD

**Issue by naman1901** [virtustream/azure-vmware-virtustream-cli-extension#30]
I'm trying to create an ExpressRoute authorization token using the CLI.

Command:
`az vmware private-cloud addauthorization --name $EXPRESSROUTE_AUTH_TOKEN_NAME --private-cloud $AVS_PRIVATE_CLOUD_NAME --resource-group $AVS_RESOURCE_GROUP --subscription $AVS_SUBSCRIPTION_ID`

The response I get is:
`BadRequest - Unable to set authorizations: One or more errors occurred. (Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: <REDACTED>.)`

The URI's contents are as follows:
`{"error":{"code":"AuthenticationFailed","message":"Authentication failed. The 'Authorization' header is missing."}}`

But when I navigate to the portal, I see that the token has been created (this outcome validates the values I pass):
![image](https://user-images.githubusercontent.com/13290002/78579965-57dbe600-784f-11ea-92ef-19d1d6313b1c.png)

**Comment by ctaggart** [comment]
This appears to be a server-side issue and not a bug in this az cli extension. I moved this to an internal bug VCFM-2811.
