### ISSUE TITLE
cluster list shows no information

### ISSUE THREAD

**Issue by jreypo** [virtustream/azure-vmware-virtustream-cli-extension#41]
Command `az vmware cluster list` returns nothing when executed on a private cloud with a cluster. 

```
$ az vmware cluster list -c avs-sku20-eus -g avs-jurey-eus -o json
[]
```

If I query the private cloud for the list of clusters again returns an empty value.

```
$ az vmware private-cloud show -n avs-sku20-eus -g avs-jurey-eus --query '[properties.clusters]' -o json
[
  []
]
```
If I ask for `properties.cluster` it returns the information of the cluster. 

```
$ az vmware private-cloud show -n avs-sku20-eus -g avs-jurey-eus --query '[properties.cluster]' -o json
[
  {
    "clusterID": 1,
    "clusterId": null,
    "clusterSize": 3,
    "hosts": [
      "esx22-r02.p01.rstn01.vmcp.vs.management",
      "esx22-r07.p01.rstn01.vmcp.vs.management",
      "esx20-r05.p01.rstn01.vmcp.vs.management"
    ]
  }
]
```

**Comment by ctaggart** [comment]
Hi @jreypo, `properties.cluster` is the management cluster. The GA API changes the name to `managementCluster` to make it more obvious:

https://github.com/Azure/az-vmware-cli/pull/31/files#diff-0e0ac10fc1060a05291b9abed982d859R24

`az cluster list` is working and displaying the same thing as `properties.clusters`.

**Comment by jreypo** [comment]
OK, I understand that. But then there is a discrepancy between what the commend lists and what the help says, cluser command help says it lists the clusters in a private cloud, not the management cluster. 

```
➜ az vmware cluster list -h
This command is from the following extension: vmware

Command
    az vmware cluster list : List clusters in a private cloud.

Arguments
    --private-cloud -c  [Required] : Name of the private cloud.
    --resource-group -g [Required] : Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.

Global Arguments
    --debug                        : Increase logging verbosity to show all debug logs.
    --help -h                      : Show this help message and exit.
    --only-show-errors             : Only show errors, suppressing warnings.
    --output -o                    : Output format.  Allowed values: json, jsonc, none, table, tsv,
                                     yaml, yamlc.  Default: table.
    --query                        : JMESPath query string. See http://jmespath.org/ for more
                                     information and examples.
    --subscription                 : Name or ID of subscription. You can configure the default
                                     subscription using `az account set -s NAME_OR_ID`.
    --verbose                      : Increase logging verbosity. Use --debug for full debug logs.

For more specific examples, use: az find "az vmware cluster list"

Please let us know how we are doing: https://aka.ms/clihats

~ 
➜
```

**Comment by ctaggart** [comment]
Correct, the `cluster list` command lists clusters in a private cloud. The management cluster is separate and will not be in that list. No clusters have been added to that private cloud. The management cluster is created when you create the private cloud.

**Comment by jreypo** [comment]
OK, so if there is only one cluster, which of course is the management cluster, then `az vmware cluster list` will return an empty value. 

I understand the reason behind showing the management cluster separated but then help for `cluster list` command should be more specific. Because on Azure Portal or AVS documentation there is no reference about the management cluster, it is assumed is the first one.
